const EasingEnum = {
    Linear: linear,
    EaseInSine: easeInSine,
    EaseOutSine: easeOutSine,
    EaseInOutSine: easeInOutSine,
    EaseInCubic: easeInCubic,
    EaseOutCubic: easeOutCubic,
    EaseInOutCubic: easeInOutCubic,
    EaseInQuint: easeInQuint,
    EaseOutQuint: easeOutQuint,
    EaseInOutQuint: easeInOutQuint,
    EaseInCirc: easeInCirc,
    EaseOutCirc: easeOutCirc,
    EaseInOutCirc: easeInOutCirc,
    EaseInElastic: easeInElastic,
    EaseOutElastic: easeOutElastic,
    EaseInOutElastic: easeInOutElastic,
    EaseInQuad: easeInQuad,
    EaseOutQuad: easeOutQuad,
    EaseInOutQuad: easeInOutQuad,
    EaseInQuart: easeInQuart,
    EaseOutQuart: easeOutQuart,
    EaseInOutQuart: easeInOutQuart,
    EaseInExpo: easeInExpo,
    EaseOutExpo: easeOutExpo,
    EaseInOutExpo: easeInOutExpo,
    EaseInBack: easeInBack,
    EaseOutBack: easeOutBack,
    EaseInOutBack: easeInOutBack,
    EaseInBounce: easeInBounce,
    EaseOutBounce: easeOutBounce,
    EaseInOutBounce: easeInOutBounce
}

